# Problem Statement and Data Description


#### Chennai House Price Prediction (Regression)

ChennaiEstate is a real estate firm based in Chennai that is involved in the property business for the past 5 years. Since, they are in the business for so long, they have enough data of all the real estate transactions in the city. They decided to venture into Analytics and have now started a division called “Chennai Estate Analytics” to give consumers as much information as possible about housings and the real estate market in Chennai. A home is often the largest and most expensive purchase a person makes in his or her lifetime. Ensuring real-estate owners have a trusted way to monitor the asset is incredibly important. Hence, they have hired you as a consultant to help them give insights and develop a model to accurately predict real estate prices. Based on the train dataset, you will need to develop a model that accurately predicts the real estate price in Chennai.

#### Data Description

### House Features


INT_SQFT – The interior Sq. Ft of the property

N_BEDROOM – The number of Bed rooms

N_BATHROOM - The number of bathrooms

N_ROOM – Total Number of Rooms

QS_ROOMS – The quality score assigned for rooms based on buyer reviews

QS_BATHROOM – The quality score assigned for bathroom based on buyer reviews

QS_BEDROOM – The quality score assigned for bedroom based on buyer reviews

QS_OVERALL – The Overall quality score assigned for the property

SALE_COND – The Sale Condition

Normal: Normal Sale
    
Abnorml: Abnormal Sale - trade, foreclosure, short sale
    
AdjLand: Adjoining Land Purchase
    
Family: Sale between family members
    
Partial: Home was not completed when last assessed
    
BUILDTYPE – The type of building

House

Commercial

Others

### Surrounding and Locality


AREA – The property in which the real estate is located

DIST_MAINROAD – The distance of the property to the main road

PARK_FACIL – Whether parking facility is available

UTILITY_AVAIL:
    
AllPub: All public Utilities (E,G,W,& S)
    
NoSewr: Electricity, Gas, and Water (Septic Tank)
    
NoSeWa: Electricity and Gas Only
    
ELO: Electricity only
    
STREET:
    
Gravel

Paved

No Access

MZZONE:
    
A: Agriculture
    
C: Commercial
    
I: Industrial
    
RH: Residential High Density
    
RL: Residential Low Density
    
RM: Residential Medium Density

### House Sale Price


PRT_ID – The Property Transaction ID assigned by ChennaiEstate

COMMIS – The Commission paid to the agent

SALES_PRICE – The total sale price of the property

# Loading the Dataset


In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("chennai_house_price_prediction.csv")
df.shape

(7109, 19)

In [4]:
df.head()

PRT_ID        AREA  INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  \
0  P03210  Karapakkam      1004            131        1.0         1.0       3   
1  P09411  Anna Nagar      1986             26        2.0         1.0       5   
2  P01812       Adyar       909             70        1.0         1.0       3   
3  P05346   Velachery      1855             14        3.0         2.0       5   
4  P06210  Karapakkam      1226             84        1.0         1.0       3   

  SALE_COND PARK_FACIL   BUILDTYPE UTILITY_AVAIL  STREET MZZONE  QS_ROOMS  \
0  AbNormal        Yes  Commercial        AllPub   Paved      A       4.0   
1  AbNormal         No  Commercial        AllPub  Gravel     RH       4.9   
2  AbNormal        Yes  Commercial           ELO  Gravel     RL       4.1   
3    Family         No      Others       NoSewr    Paved      I       4.7   
4  AbNormal        Yes      Others        AllPub  Gravel      C       3.0   

   QS_BATHROOM  QS_BEDROOM  QS_OVERALL  COMMIS  SALES_PRICE  
0          3.9         4.9       4.330  144400      7600000  
1          4.2         2.5       3.765  304049     21717770  
2          3.8         2.2       3.090   92114     13159200  
3          3.9         3.6       4.010   77042      9630290  
4          2.5         4.1       3.290   74063      7406250

# Data Manipulation


# 1. Drop Duplicates (if any)


In [5]:
df.drop_duplicates()

PRT_ID        AREA  INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  \
0     P03210  Karapakkam      1004            131        1.0         1.0   
1     P09411  Anna Nagar      1986             26        2.0         1.0   
2     P01812       Adyar       909             70        1.0         1.0   
3     P05346   Velachery      1855             14        3.0         2.0   
4     P06210  Karapakkam      1226             84        1.0         1.0   
...      ...         ...       ...            ...        ...         ...   
7104  P03834  Karapakkam       598             51        1.0         1.0   
7105  P10000   Velachery      1897             52        3.0         2.0   
7106  P09594   Velachery      1614            152        2.0         1.0   
7107  P06508  Karapakkam       787             40        1.0         1.0   
7108  P09794   Velachery      1896            156        3.0         2.0   

      N_ROOM    SALE_COND PARK_FACIL   BUILDTYPE UTILITY_AVAIL     STREET  \
0          3     AbNormal        Yes  Commercial        AllPub      Paved   
1          5     AbNormal         No  Commercial        AllPub     Gravel   
2          3     AbNormal        Yes  Commercial           ELO     Gravel   
3          5       Family         No      Others       NoSewr       Paved   
4          3     AbNormal        Yes      Others        AllPub     Gravel   
...      ...          ...        ...         ...           ...        ...   
7104       2      AdjLand         No      Others           ELO  No Access   
7105       5       Family        Yes      Others        NoSeWa  No Access   
7106       4  Normal Sale         No       House        NoSeWa     Gravel   
7107       2      Partial        Yes  Commercial           ELO      Paved   
7108       5      Partial        Yes      Others           ELO      Paved   

     MZZONE  QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  COMMIS  \
0         A       4.0          3.9         4.9       4.330  144400   
1        RH       4.9          4.2         2.5       3.765  304049   
2        RL       4.1          3.8         2.2       3.090   92114   
3         I       4.7          3.9         3.6       4.010   77042   
4         C       3.0          2.5         4.1       3.290   74063   
...     ...       ...          ...         ...         ...     ...   
7104     RM       3.0          2.2         2.4       2.520  107060   
7105     RH       3.6          4.5         3.3       3.920  205551   
7106      I       4.3          4.2         2.9       3.840  167028   
7107     RL       4.6          3.8         4.1       4.160  119098   
7108      I       3.1          3.5         4.3       3.640   79812   

      SALES_PRICE  
0         7600000  
1        21717770  
2        13159200  
3         9630290  
4         7406250  
...           ...  
7104      5353000  
7105     10818480  
7106      8351410  
7107      8507000  
7108      9976480  

[7109 rows x 19 columns]

In [6]:
df.shape

(7109, 19)

We have no duplicates. Hence the shape did not change here.

# Missing Values


In [7]:
# missing values

df.isnull().sum()

PRT_ID            0
AREA              0
INT_SQFT          0
DIST_MAINROAD     0
N_BEDROOM         1
N_BATHROOM        5
N_ROOM            0
SALE_COND         0
PARK_FACIL        0
BUILDTYPE         0
UTILITY_AVAIL     0
STREET            0
MZZONE            0
QS_ROOMS          0
QS_BATHROOM       0
QS_BEDROOM        0
QS_OVERALL       48
COMMIS            0
SALES_PRICE       0
dtype: int64

### 1. N_BEDROOM


In [8]:
df['N_BEDROOM'].mode()

0    1.0
dtype: float64

In [9]:
df['N_BEDROOM'].fillna(value = (df['N_BEDROOM'].mode()[0]), inplace=True)

### 2. N_BATHROOM


In [10]:
df.loc[df['N_BATHROOM'].isnull()==True]

PRT_ID        AREA  INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  \
70    P05304  Anna Nagar      1589             39        1.0         NaN   
5087  P01333    Chrompet      1016            105        1.0         NaN   
6134  P01332    Chormpet       916            173        1.0         NaN   
6371  P01189    Chrompet      1035             90        1.0         NaN   
6535  P09189  Anna Nagar      1864            184        2.0         NaN   

      N_ROOM    SALE_COND PARK_FACIL BUILDTYPE UTILITY_AVAIL     STREET  \
70         4      Partial         No    Others        AllPub     Gravel   
5087       3     AbNormal        Yes    Others       NoSewr      Gravel   
6134       3  Normal Sale        Yes    Others           ELO      Paved   
6371       3      Partial         No    Others        NoSeWa  No Access   
6535       5       Family        Yes    Others       NoSewr       Paved   

     MZZONE  QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  COMMIS  \
70       RL       2.1          2.5         4.5        3.16   85486   
5087     RM       3.2          4.2         2.0        3.24  106479   
6134     RL       3.4          3.5         3.0         NaN   44237   
6371     RM       2.3          3.5         3.2        3.05   24823   
6535     RM       3.3          3.7         4.7        3.96  124455   

      SALES_PRICE  
70       12212350  
5087     10647920  
6134      8847420  
6371      8274200  
6535     15556920

In [11]:
for i in range(0, len(df)):
    if pd.isnull(df['N_BATHROOM'][i])==True:
        if (df['N_BEDROOM'][i] == 1.0):
            df['N_BATHROOM'][i] = 1.0
        else: 
            df['N_BATHROOM'][i] = 2.0

C:\Users\Parth Anand\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Parth Anand\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


### 3. QS_OVERALL


In [12]:
temp = (df['QS_ROOMS'] + df['QS_BATHROOM'] + df['QS_BEDROOM'])/3
pd.concat([df['QS_ROOMS'], df['QS_BATHROOM'], df['QS_BEDROOM'], temp], axis=1).head(10)

QS_ROOMS  QS_BATHROOM  QS_BEDROOM         0
0       4.0          3.9         4.9  4.266667
1       4.9          4.2         2.5  3.866667
2       4.1          3.8         2.2  3.366667
3       4.7          3.9         3.6  4.066667
4       3.0          2.5         4.1  3.200000
5       4.5          2.6         3.1  3.400000
6       3.6          2.1         2.5  2.733333
7       2.4          4.5         2.1  3.000000
8       2.9          3.7         4.0  3.533333
9       3.1          3.1         3.3  3.166667

In [13]:
df.loc[df['QS_OVERALL'].isnull()==True].shape

(48, 19)

In [14]:
def fill_na(x):
    return ((x['QS_ROOMS'] + x['QS_BATHROOM'] + x['QS_BEDROOM'])/3)

In [15]:
df['QS_OVERALL'] =  df.apply(lambda x: fill_na(x) if pd.isnull(x['QS_OVERALL']) else x['QS_OVERALL'], axis=1)

In [16]:
df.isnull().sum()

PRT_ID           0
AREA             0
INT_SQFT         0
DIST_MAINROAD    0
N_BEDROOM        0
N_BATHROOM       0
N_ROOM           0
SALE_COND        0
PARK_FACIL       0
BUILDTYPE        0
UTILITY_AVAIL    0
STREET           0
MZZONE           0
QS_ROOMS         0
QS_BATHROOM      0
QS_BEDROOM       0
QS_OVERALL       0
COMMIS           0
SALES_PRICE      0
dtype: int64

# Data Types

In [17]:
df.dtypes

PRT_ID            object
AREA              object
INT_SQFT           int64
DIST_MAINROAD      int64
N_BEDROOM        float64
N_BATHROOM       float64
N_ROOM             int64
SALE_COND         object
PARK_FACIL        object
BUILDTYPE         object
UTILITY_AVAIL     object
STREET            object
MZZONE            object
QS_ROOMS         float64
QS_BATHROOM      float64
QS_BEDROOM       float64
QS_OVERALL       float64
COMMIS             int64
SALES_PRICE        int64
dtype: object

In [18]:
# data type of n_bedroom, n_room, n_bathroom

df=df.astype({'N_BEDROOM':'object','N_BATHROOM':'object','N_ROOM':'object'})

# Replace categories


In [19]:
temp = ['AREA','N_BEDROOM','N_BATHROOM','N_ROOM','SALE_COND','PARK_FACIL','BUILDTYPE','UTILITY_AVAIL','STREET','MZZONE']
for i in temp:
    print('************ Value Count in', i, '************')
    print(df[i].value_counts())
    print('')

************ Value Count in AREA ************
Chrompet      1681
Karapakkam    1363
KK Nagar       996
Velachery      979
Anna Nagar     783
Adyar          773
T Nagar        496
Chrompt          9
Chrmpet          6
Chormpet         6
TNagar           5
Ana Nagar        3
Karapakam        3
Ann Nagar        2
Velchery         2
KKNagar          1
Adyr             1
Name: AREA, dtype: int64

************ Value Count in N_BEDROOM ************
1.0    3796
2.0    2352
3.0     707
4.0     254
Name: N_BEDROOM, dtype: int64

************ Value Count in N_BATHROOM ************
1.0    5593
2.0    1516
Name: N_BATHROOM, dtype: int64

************ Value Count in N_ROOM ************
4    2563
3    2125
5    1246
2     921
6     254
Name: N_ROOM, dtype: int64

************ Value Count in SALE_COND ************
AdjLand        1433
Partial        1429
Normal Sale    1423
AbNormal       1406
Family         1403
Adj Land          6
Ab Normal         5
Partiall          3
PartiaLl          1
Name: SALE

### Update names in column


AREA

SALE_COND

PARK_FACIL

BUILDTYPE

UTILITY_AVAIL

STREET

In [20]:
df['PARK_FACIL'].replace({'Noo':'No'}, inplace = True)
df['PARK_FACIL'].value_counts()

Yes    3587
No     3522
Name: PARK_FACIL, dtype: int64

In [21]:
df['AREA'].replace({'TNagar':'T Nagar', 'Adyr': 'Adyar', 'KKNagar': 'KK Nagar',  
                    'Chrompt': 'Chrompet', 'Chormpet': 'Chrompet','Chrmpet': 'Chrompet',
                    'Ana Nagar': 'Anna Nagar', 'Ann Nagar': 'Anna Nagar',
                     'Karapakam': 'Karapakkam' , 'Velchery': 'Velachery'}, inplace = True)

In [22]:
df['AREA'].value_counts()

Chrompet      1702
Karapakkam    1366
KK Nagar       997
Velachery      981
Anna Nagar     788
Adyar          774
T Nagar        501
Name: AREA, dtype: int64

In [23]:
df['SALE_COND'].replace({'PartiaLl':'Partial', 'Partiall': 'Partial', 
                         'Adj Land': 'AdjLand',  
                         'Ab Normal': 'AbNormal'}, inplace = True)
df['SALE_COND'].value_counts()

AdjLand        1439
Partial        1433
Normal Sale    1423
AbNormal       1411
Family         1403
Name: SALE_COND, dtype: int64

In [24]:
df['BUILDTYPE'].replace({'Comercial':'Commercial', 'Other': 'Others'},inplace = True)
df['UTILITY_AVAIL'].replace({'All Pub':'AllPub'},inplace = True)
df['STREET'].replace({'NoAccess':'No Access', 'Pavd':'Paved'},inplace = True)


# Dividing dependent and independent variables

In [25]:
df.drop(['PRT_ID'], axis=1, inplace = True)

In [26]:
df = pd.get_dummies(df)

In [27]:
x = df.drop('SALES_PRICE', axis=1)
y= df['SALES_PRICE']

# Train Test Split

In [29]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, shuffle=False)

train_x.shape, valid_x.shape, train_y.shape, valid_y.shape

((5331, 48), (1778, 48), (5331,), (1778,))

# Ensemble Modelling

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [31]:
model1 = LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([13134012.6924295 ,  5804118.77330469,  6759679.96102115,
        15042841.39516595,  7836457.77842593, 17106085.75413363,
        14820923.21963336,  7816235.92781539, 11805172.59755698,
         6773935.98096181]),
 0.9564858152281903)

In [39]:
model2 = KNeighborsRegressor(n_neighbors=10)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([14947371. ,  8081913.5,  7099564.5, 13866923. ,  8209924.5,
        16984544. , 14173517. ,  9026295. ,  8518724.5,  8397148. ]),
 0.48426437767046027)

In [33]:
model3 = DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([12039804.        ,  6306120.50505051,  6306120.50505051,
        13471097.54491018,  8541052.66666667, 18751690.55555556,
        14205712.29299363,  7454747.32394366,  9285568.05970149,
         5730622.78761062]),
 0.9403496965796004)

# 1. Averaging

In [40]:
from statistics import mean
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mean([pred1[i], pred2[i], pred3[i]]))

In [41]:
from sklearn.metrics import r2_score

In [42]:
r2_score(valid_y, final_pred)

0.9116159554312355

# Weighted Averaging


In [43]:
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mean([pred1[i], pred1[i], pred2[i], pred3[i], pred3[i]]))

In [44]:
r2_score(valid_y, final_pred)

0.9482814417466635

Giving More weightage to linear regression and decission tree regressor's predictions

# Rank Averaging

In [45]:
m1_score= model1.score(valid_x, valid_y)
m2_score= model2.score(valid_x, valid_y)
m3_score= model3.score(valid_x, valid_y)
m1_score, m2_score, m3_score

(0.9564858152281903, 0.48426437767046027, 0.9403496965796004)

In [46]:
index_ = [1,2,3]
valid_r2 = [m1_score,m2_score,m3_score]

rank_eval = pd.DataFrame({
    'score':valid_r2
}, index = index_)
rank_eval

score
1  0.956486
2  0.484264
3  0.940350

In [47]:
sorted_rank = rank_eval.sort_values('score')
sorted_rank

score
2  0.484264
3  0.940350
1  0.956486

In [48]:
sorted_rank['rank'] = [i for i in range(1,4)]
sorted_rank

score  rank
2  0.484264     1
3  0.940350     2
1  0.956486     3

In [49]:
sorted_rank['weight'] = sorted_rank['rank']/sorted_rank['rank'].sum()
sorted_rank

score  rank    weight
2  0.484264     1  0.166667
3  0.940350     2  0.333333
1  0.956486     3  0.500000

In [50]:
wt_pred1 = pred1*float(sorted_rank.loc[[1],['weight']].values)
wt_pred2 = pred2*float(sorted_rank.loc[[2],['weight']].values)
wt_pred3 = pred3*float(sorted_rank.loc[[3],['weight']].values)
ranked_prediction = wt_pred1 + wt_pred2 + wt_pred3
ranked_prediction

array([13071502.84621475,  6351085.13833584,  6665140.89886075, ...,
        9204383.34028297,  9460449.16151756, 10213594.69513709])

In [51]:
r2_score(valid_y, ranked_prediction)

0.9553755101611895